// Builds a small texture atlas from public/textures/*.png (populated by
// scripts/sync-textures.sh: DABB preferred, vanilla fallback) and hands the scene
// a per-block-type geometry (per-face UVs baked into the atlas) + material.
//
// Faces use BoxGeometry material order [+x, -x, +y, -y, +z, -z]. Directional blocks
// put their "front" texture on +Z; the scene rotates each instance so +Z aligns with
// the block's facing. Glass is alpha-tested (opaque frame / clear pane), slime is
// translucent; everything else is opaque.
import * as THREE from 'three'
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js'

const TEX_NAMES = [
  'stone', 'glass', 'slime', 'redstone_block',
  'piston_top', 'piston_top_sticky', 'piston_side', 'piston_side_sticky',
  'piston_bottom', 'piston_bottom_sticky',
  'observer_front', 'observer_back', 'observer_side', 'observer_top',
  // DABB's "powered" observer reskins all 4 distinct faces (front/side/top/back), not just the
  // back arrow - see ignore/DABB/assets/minecraft/models/block/observer_powered.json.
  'observer_front_on', 'observer_side_on', 'observer_top_on', 'observer_back_on',
  // Every other Minecraft 1.12 block id with a real block texture (see blocks.ts's BLOCK_TYPES
  // comment for what's deliberately left out - entity-rendered/textureless blocks like chests,
  // beds, skulls, and barrier). Generated by cross-referencing the actual files copied into
  // public/textures/ against the real Minecraft 1.12 block registry (PrismarineJS/minecraft-data)
  // - not hand-typed, to avoid guessing wrong ids/filenames from memory.
  'anvil', 'anvil_top', 'beacon', 'bedrock', 'bone_block_side', 'bone_block_top', 'bookshelf', 'brewing_stand',
  'brick', 'cactus_bottom', 'cactus_side', 'cactus_top', 'cake_bottom', 'cake_side', 'cake_top', 'cauldron_bottom',
  'cauldron_side', 'cauldron_top', 'chain_command_block_back', 'chain_command_block_front', 'chain_command_block_side', 'chorus_flower', 'chorus_plant', 'clay',
  'coal_block', 'coal_ore', 'cobblestone', 'cobblestone_mossy', 'cocoa_stage_2', 'command_block_back', 'command_block_front', 'command_block_side',
  'comparator_off', 'comparator_on', 'concrete_powder_white', 'concrete_white', 'crafting_table_side', 'crafting_table_top', 'daylight_detector_inverted_side', 'daylight_detector_inverted_top',
  'daylight_detector_side', 'daylight_detector_top', 'diamond_block', 'diamond_ore', 'dirt', 'dispenser_front', 'door_acacia_lower', 'door_birch_lower',
  'door_dark_oak_lower', 'door_iron_lower', 'door_jungle_lower', 'door_spruce_lower', 'door_wood_lower', 'dragon_egg', 'dropper_front', 'emerald_block',
  'emerald_ore', 'enchanting_table_bottom', 'enchanting_table_side', 'enchanting_table_top', 'end_bricks', 'end_rod', 'end_stone', 'endframe_side',
  'endframe_top', 'farmland_dry', 'flower_pot', 'frosted_ice_0', 'furnace_front_on', 'furnace_side', 'furnace_top', 'glazed_terracotta_black',
  'glazed_terracotta_blue', 'glazed_terracotta_brown', 'glazed_terracotta_cyan', 'glazed_terracotta_gray', 'glazed_terracotta_green', 'glazed_terracotta_light_blue', 'glazed_terracotta_lime', 'glazed_terracotta_magenta',
  'glazed_terracotta_orange', 'glazed_terracotta_pink', 'glazed_terracotta_purple', 'glazed_terracotta_red', 'glazed_terracotta_silver', 'glazed_terracotta_white', 'glazed_terracotta_yellow', 'glowstone',
  'gold_block', 'gold_ore', 'grass_path_side', 'grass_path_top', 'grass_side', 'grass_top', 'gravel', 'hardened_clay',
  'hardened_clay_stained_white', 'hay_block_side', 'hay_block_top', 'hopper_outside', 'hopper_top', 'ice', 'ice_packed', 'iron_bars',
  'iron_block', 'iron_ore', 'iron_trapdoor', 'jukebox_side', 'jukebox_top', 'ladder', 'lapis_block', 'lapis_ore',
  'leaves_acacia', 'leaves_oak', 'log_acacia', 'log_acacia_top', 'log_oak', 'log_oak_top', 'magma', 'melon_side',
  'melon_top', 'mob_spawner', 'mushroom_block_skin_brown', 'mushroom_block_skin_red', 'mycelium_side', 'mycelium_top', 'nether_brick', 'nether_wart_block',
  'netherrack', 'noteblock', 'obsidian', 'planks_acacia', 'planks_birch', 'planks_jungle', 'planks_oak', 'planks_spruce',
  'prismarine_rough', 'pumpkin_face_off', 'pumpkin_face_on', 'pumpkin_top', 'purpur_block', 'purpur_pillar', 'purpur_pillar_top', 'quartz_block_bottom',
  'quartz_block_side', 'quartz_block_top', 'quartz_ore', 'red_nether_brick', 'red_sandstone_bottom', 'red_sandstone_normal', 'red_sandstone_top', 'redstone_lamp_off',
  'redstone_lamp_on', 'redstone_ore', 'repeater_off', 'repeater_on', 'repeating_command_block_back', 'repeating_command_block_front', 'repeating_command_block_side', 'sand',
  'sandstone_bottom', 'sandstone_normal', 'sandstone_top', 'sea_lantern', 'shulker_top_black', 'shulker_top_blue', 'shulker_top_brown', 'shulker_top_cyan',
  'shulker_top_gray', 'shulker_top_green', 'shulker_top_light_blue', 'shulker_top_lime', 'shulker_top_magenta', 'shulker_top_orange', 'shulker_top_pink', 'shulker_top_purple',
  'shulker_top_red', 'shulker_top_silver', 'shulker_top_white', 'shulker_top_yellow', 'snow', 'soul_sand', 'sponge', 'stone_slab_side',
  'stone_slab_top', 'stonebrick', 'structure_block', 'tnt_bottom', 'tnt_side', 'tnt_top', 'trapdoor', 'waterlily',
  'wool_colored_white',
  // The piston body's own front face while extended (the head has left, exposing the plain
  // track/frame) - see the piston-inner overlay in animatedScene.ts.
  'piston_inner',
] as const
type TexName = (typeof TEX_NAMES)[number]

// Face textures in BoxGeometry material order [+x, -x, +y, -y, +z, -z].
// A block's "front" (the head/face) sits on the axis returned by frontAxis(); the scene
// rotates each instance so that axis aligns with the block's facing direction. Pistons put
// their head on +Y so all four *vertical* faces are the "sides" and share the same upward
// texture orientation (avoids the side texture looking rotated/garbled face-to-face).
const FACES: Record<number, [TexName, TexName, TexName, TexName, TexName, TexName]> = {
  1: ['stone', 'stone', 'stone', 'stone', 'stone', 'stone'],
  20: ['glass', 'glass', 'glass', 'glass', 'glass', 'glass'],
  165: ['slime', 'slime', 'slime', 'slime', 'slime', 'slime'],
  152: ['redstone_block', 'redstone_block', 'redstone_block', 'redstone_block', 'redstone_block', 'redstone_block'],
  // pistons: head on +Y, back on -Y, piston_side on the 4 vertical faces
  33: ['piston_side', 'piston_side', 'piston_top', 'piston_bottom', 'piston_side', 'piston_side'],
  29: ['piston_side_sticky', 'piston_side_sticky', 'piston_top_sticky', 'piston_bottom_sticky', 'piston_side_sticky', 'piston_side_sticky'],
  34: ['piston_side', 'piston_side', 'piston_top', 'piston_side', 'piston_side', 'piston_side'],
  // observer: front (eyes) on +Z, back (output) on -Z, arrow textures on the other four
  218: ['observer_side', 'observer_side', 'observer_top', 'observer_top', 'observer_front', 'observer_back'],

  // Every other real Minecraft 1.12 block with a texture, generated (not hand-typed) from the
  // real block registry cross-referenced against public/textures/ - see the TEX_NAMES comment
  // above. Non-cube blocks (stairs, slabs, fences, doors, etc.) render as a full textured cube -
  // a shape approximation, not pixel-accurate geometry; a handful of entity-rendered/textureless
  // blocks (chest, bed, skull, barrier) are left out entirely and fall back to the unknown color.
  2: ['grass_side','grass_side','grass_top','dirt','grass_side','grass_side'],
  3: ['dirt','dirt','dirt','dirt','dirt','dirt'],
  4: ['cobblestone','cobblestone','cobblestone','cobblestone','cobblestone','cobblestone'],
  5: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  7: ['bedrock','bedrock','bedrock','bedrock','bedrock','bedrock'],
  12: ['sand','sand','sand','sand','sand','sand'],
  13: ['gravel','gravel','gravel','gravel','gravel','gravel'],
  14: ['gold_ore','gold_ore','gold_ore','gold_ore','gold_ore','gold_ore'],
  15: ['iron_ore','iron_ore','iron_ore','iron_ore','iron_ore','iron_ore'],
  16: ['coal_ore','coal_ore','coal_ore','coal_ore','coal_ore','coal_ore'],
  17: ['log_oak','log_oak','log_oak_top','log_oak_top','log_oak','log_oak'],
  18: ['leaves_oak','leaves_oak','leaves_oak','leaves_oak','leaves_oak','leaves_oak'],
  19: ['sponge','sponge','sponge','sponge','sponge','sponge'],
  21: ['lapis_ore','lapis_ore','lapis_ore','lapis_ore','lapis_ore','lapis_ore'],
  22: ['lapis_block','lapis_block','lapis_block','lapis_block','lapis_block','lapis_block'],
  23: ['dispenser_front','dispenser_front','furnace_top','furnace_top','dispenser_front','dispenser_front'],
  24: ['sandstone_normal','sandstone_normal','sandstone_top','sandstone_bottom','sandstone_normal','sandstone_normal'],
  25: ['noteblock','noteblock','noteblock','noteblock','noteblock','noteblock'],
  35: ['wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white'],
  41: ['gold_block','gold_block','gold_block','gold_block','gold_block','gold_block'],
  42: ['iron_block','iron_block','iron_block','iron_block','iron_block','iron_block'],
  43: ['stone_slab_side','stone_slab_side','stone_slab_top','stone_slab_top','stone_slab_side','stone_slab_side'],
  44: ['stone_slab_side','stone_slab_side','stone_slab_top','stone_slab_top','stone_slab_side','stone_slab_side'],
  45: ['brick','brick','brick','brick','brick','brick'],
  46: ['tnt_side','tnt_side','tnt_top','tnt_bottom','tnt_side','tnt_side'],
  47: ['bookshelf','bookshelf','bookshelf','bookshelf','bookshelf','bookshelf'],
  48: ['cobblestone_mossy','cobblestone_mossy','cobblestone_mossy','cobblestone_mossy','cobblestone_mossy','cobblestone_mossy'],
  49: ['obsidian','obsidian','obsidian','obsidian','obsidian','obsidian'],
  52: ['mob_spawner','mob_spawner','mob_spawner','mob_spawner','mob_spawner','mob_spawner'],
  53: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  56: ['diamond_ore','diamond_ore','diamond_ore','diamond_ore','diamond_ore','diamond_ore'],
  57: ['diamond_block','diamond_block','diamond_block','diamond_block','diamond_block','diamond_block'],
  58: ['crafting_table_side','crafting_table_side','crafting_table_top','crafting_table_top','crafting_table_side','crafting_table_side'],
  60: ['farmland_dry','farmland_dry','farmland_dry','farmland_dry','farmland_dry','farmland_dry'],
  61: ['furnace_side','furnace_side','furnace_top','furnace_top','furnace_side','furnace_side'],
  62: ['furnace_front_on','furnace_front_on','furnace_top','furnace_top','furnace_front_on','furnace_front_on'],
  64: ['door_wood_lower','door_wood_lower','door_wood_lower','door_wood_lower','door_wood_lower','door_wood_lower'],
  65: ['ladder','ladder','ladder','ladder','ladder','ladder'],
  67: ['cobblestone','cobblestone','cobblestone','cobblestone','cobblestone','cobblestone'],
  71: ['door_iron_lower','door_iron_lower','door_iron_lower','door_iron_lower','door_iron_lower','door_iron_lower'],
  73: ['redstone_ore','redstone_ore','redstone_ore','redstone_ore','redstone_ore','redstone_ore'],
  74: ['redstone_ore','redstone_ore','redstone_ore','redstone_ore','redstone_ore','redstone_ore'],
  78: ['snow','snow','snow','snow','snow','snow'],
  79: ['ice','ice','ice','ice','ice','ice'],
  80: ['snow','snow','snow','snow','snow','snow'],
  81: ['cactus_side','cactus_side','cactus_top','cactus_bottom','cactus_side','cactus_side'],
  82: ['clay','clay','clay','clay','clay','clay'],
  84: ['jukebox_side','jukebox_side','jukebox_top','jukebox_top','jukebox_side','jukebox_side'],
  85: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  86: ['pumpkin_face_off','pumpkin_face_off','pumpkin_top','pumpkin_top','pumpkin_face_off','pumpkin_face_off'],
  87: ['netherrack','netherrack','netherrack','netherrack','netherrack','netherrack'],
  88: ['soul_sand','soul_sand','soul_sand','soul_sand','soul_sand','soul_sand'],
  89: ['glowstone','glowstone','glowstone','glowstone','glowstone','glowstone'],
  91: ['pumpkin_face_on','pumpkin_face_on','pumpkin_top','pumpkin_top','pumpkin_face_on','pumpkin_face_on'],
  92: ['cake_side','cake_side','cake_top','cake_bottom','cake_side','cake_side'],
  93: ['repeater_off','repeater_off','repeater_off','repeater_off','repeater_off','repeater_off'],
  94: ['repeater_on','repeater_on','repeater_on','repeater_on','repeater_on','repeater_on'],
  95: ['glass','glass','glass','glass','glass','glass'],
  96: ['trapdoor','trapdoor','trapdoor','trapdoor','trapdoor','trapdoor'],
  97: ['stone','stone','stone','stone','stone','stone'],
  98: ['stonebrick','stonebrick','stonebrick','stonebrick','stonebrick','stonebrick'],
  99: ['mushroom_block_skin_brown','mushroom_block_skin_brown','mushroom_block_skin_brown','mushroom_block_skin_brown','mushroom_block_skin_brown','mushroom_block_skin_brown'],
  100: ['mushroom_block_skin_red','mushroom_block_skin_red','mushroom_block_skin_red','mushroom_block_skin_red','mushroom_block_skin_red','mushroom_block_skin_red'],
  101: ['iron_bars','iron_bars','iron_bars','iron_bars','iron_bars','iron_bars'],
  102: ['glass','glass','glass','glass','glass','glass'],
  103: ['melon_side','melon_side','melon_top','melon_top','melon_side','melon_side'],
  107: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  108: ['brick','brick','brick','brick','brick','brick'],
  109: ['stonebrick','stonebrick','stonebrick','stonebrick','stonebrick','stonebrick'],
  110: ['mycelium_side','mycelium_side','mycelium_top','mycelium_top','mycelium_side','mycelium_side'],
  111: ['waterlily','waterlily','waterlily','waterlily','waterlily','waterlily'],
  112: ['nether_brick','nether_brick','nether_brick','nether_brick','nether_brick','nether_brick'],
  113: ['nether_brick','nether_brick','nether_brick','nether_brick','nether_brick','nether_brick'],
  114: ['nether_brick','nether_brick','nether_brick','nether_brick','nether_brick','nether_brick'],
  116: ['enchanting_table_side','enchanting_table_side','enchanting_table_top','enchanting_table_bottom','enchanting_table_side','enchanting_table_side'],
  117: ['brewing_stand','brewing_stand','brewing_stand','brewing_stand','brewing_stand','brewing_stand'],
  118: ['cauldron_side','cauldron_side','cauldron_top','cauldron_bottom','cauldron_side','cauldron_side'],
  120: ['endframe_side','endframe_side','endframe_top','endframe_side','endframe_side','endframe_side'],
  121: ['end_stone','end_stone','end_stone','end_stone','end_stone','end_stone'],
  122: ['dragon_egg','dragon_egg','dragon_egg','dragon_egg','dragon_egg','dragon_egg'],
  123: ['redstone_lamp_off','redstone_lamp_off','redstone_lamp_off','redstone_lamp_off','redstone_lamp_off','redstone_lamp_off'],
  124: ['redstone_lamp_on','redstone_lamp_on','redstone_lamp_on','redstone_lamp_on','redstone_lamp_on','redstone_lamp_on'],
  125: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  126: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  127: ['cocoa_stage_2','cocoa_stage_2','cocoa_stage_2','cocoa_stage_2','cocoa_stage_2','cocoa_stage_2'],
  128: ['sandstone_normal','sandstone_normal','sandstone_top','sandstone_bottom','sandstone_normal','sandstone_normal'],
  129: ['emerald_ore','emerald_ore','emerald_ore','emerald_ore','emerald_ore','emerald_ore'],
  133: ['emerald_block','emerald_block','emerald_block','emerald_block','emerald_block','emerald_block'],
  134: ['planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce'],
  135: ['planks_birch','planks_birch','planks_birch','planks_birch','planks_birch','planks_birch'],
  136: ['planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle'],
  137: ['command_block_side','command_block_side','command_block_front','command_block_back','command_block_side','command_block_side'],
  138: ['beacon','beacon','beacon','beacon','beacon','beacon'],
  139: ['cobblestone','cobblestone','cobblestone','cobblestone','cobblestone','cobblestone'],
  140: ['flower_pot','flower_pot','flower_pot','flower_pot','flower_pot','flower_pot'],
  145: ['anvil','anvil','anvil_top','anvil_top','anvil','anvil'],
  149: ['comparator_off','comparator_off','comparator_off','comparator_off','comparator_off','comparator_off'],
  150: ['comparator_on','comparator_on','comparator_on','comparator_on','comparator_on','comparator_on'],
  151: ['daylight_detector_side','daylight_detector_side','daylight_detector_top','daylight_detector_top','daylight_detector_side','daylight_detector_side'],
  153: ['quartz_ore','quartz_ore','quartz_ore','quartz_ore','quartz_ore','quartz_ore'],
  154: ['hopper_outside','hopper_outside','hopper_top','hopper_outside','hopper_outside','hopper_outside'],
  155: ['quartz_block_side','quartz_block_side','quartz_block_top','quartz_block_bottom','quartz_block_side','quartz_block_side'],
  156: ['quartz_block_side','quartz_block_side','quartz_block_top','quartz_block_bottom','quartz_block_side','quartz_block_side'],
  158: ['dropper_front','dropper_front','furnace_top','furnace_top','dropper_front','dropper_front'],
  159: ['hardened_clay_stained_white','hardened_clay_stained_white','hardened_clay_stained_white','hardened_clay_stained_white','hardened_clay_stained_white','hardened_clay_stained_white'],
  160: ['glass','glass','glass','glass','glass','glass'],
  161: ['leaves_acacia','leaves_acacia','leaves_acacia','leaves_acacia','leaves_acacia','leaves_acacia'],
  162: ['log_acacia','log_acacia','log_acacia_top','log_acacia_top','log_acacia','log_acacia'],
  163: ['planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia'],
  164: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  167: ['iron_trapdoor','iron_trapdoor','iron_trapdoor','iron_trapdoor','iron_trapdoor','iron_trapdoor'],
  168: ['prismarine_rough','prismarine_rough','prismarine_rough','prismarine_rough','prismarine_rough','prismarine_rough'],
  169: ['sea_lantern','sea_lantern','sea_lantern','sea_lantern','sea_lantern','sea_lantern'],
  170: ['hay_block_side','hay_block_side','hay_block_top','hay_block_top','hay_block_side','hay_block_side'],
  171: ['wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white','wool_colored_white'],
  172: ['hardened_clay','hardened_clay','hardened_clay','hardened_clay','hardened_clay','hardened_clay'],
  173: ['coal_block','coal_block','coal_block','coal_block','coal_block','coal_block'],
  174: ['ice_packed','ice_packed','ice_packed','ice_packed','ice_packed','ice_packed'],
  178: ['daylight_detector_inverted_side','daylight_detector_inverted_side','daylight_detector_inverted_top','daylight_detector_inverted_top','daylight_detector_inverted_side','daylight_detector_inverted_side'],
  179: ['red_sandstone_normal','red_sandstone_normal','red_sandstone_top','red_sandstone_bottom','red_sandstone_normal','red_sandstone_normal'],
  180: ['red_sandstone_normal','red_sandstone_normal','red_sandstone_top','red_sandstone_bottom','red_sandstone_normal','red_sandstone_normal'],
  181: ['red_sandstone_normal','red_sandstone_normal','red_sandstone_top','red_sandstone_bottom','red_sandstone_normal','red_sandstone_normal'],
  182: ['red_sandstone_normal','red_sandstone_normal','red_sandstone_top','red_sandstone_bottom','red_sandstone_normal','red_sandstone_normal'],
  183: ['planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce'],
  184: ['planks_birch','planks_birch','planks_birch','planks_birch','planks_birch','planks_birch'],
  185: ['planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle'],
  186: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  187: ['planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia'],
  188: ['planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce','planks_spruce'],
  189: ['planks_birch','planks_birch','planks_birch','planks_birch','planks_birch','planks_birch'],
  190: ['planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle','planks_jungle'],
  191: ['planks_oak','planks_oak','planks_oak','planks_oak','planks_oak','planks_oak'],
  192: ['planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia','planks_acacia'],
  193: ['door_spruce_lower','door_spruce_lower','door_spruce_lower','door_spruce_lower','door_spruce_lower','door_spruce_lower'],
  194: ['door_birch_lower','door_birch_lower','door_birch_lower','door_birch_lower','door_birch_lower','door_birch_lower'],
  195: ['door_jungle_lower','door_jungle_lower','door_jungle_lower','door_jungle_lower','door_jungle_lower','door_jungle_lower'],
  196: ['door_acacia_lower','door_acacia_lower','door_acacia_lower','door_acacia_lower','door_acacia_lower','door_acacia_lower'],
  197: ['door_dark_oak_lower','door_dark_oak_lower','door_dark_oak_lower','door_dark_oak_lower','door_dark_oak_lower','door_dark_oak_lower'],
  198: ['end_rod','end_rod','end_rod','end_rod','end_rod','end_rod'],
  199: ['chorus_plant','chorus_plant','chorus_plant','chorus_plant','chorus_plant','chorus_plant'],
  200: ['chorus_flower','chorus_flower','chorus_flower','chorus_flower','chorus_flower','chorus_flower'],
  201: ['purpur_block','purpur_block','purpur_block','purpur_block','purpur_block','purpur_block'],
  202: ['purpur_pillar','purpur_pillar','purpur_pillar_top','purpur_pillar_top','purpur_pillar','purpur_pillar'],
  203: ['purpur_block','purpur_block','purpur_block','purpur_block','purpur_block','purpur_block'],
  204: ['purpur_block','purpur_block','purpur_block','purpur_block','purpur_block','purpur_block'],
  205: ['purpur_block','purpur_block','purpur_block','purpur_block','purpur_block','purpur_block'],
  206: ['end_bricks','end_bricks','end_bricks','end_bricks','end_bricks','end_bricks'],
  208: ['grass_path_side','grass_path_side','grass_path_top','grass_path_top','grass_path_side','grass_path_side'],
  210: ['repeating_command_block_side','repeating_command_block_side','repeating_command_block_front','repeating_command_block_back','repeating_command_block_side','repeating_command_block_side'],
  211: ['chain_command_block_side','chain_command_block_side','chain_command_block_front','chain_command_block_back','chain_command_block_side','chain_command_block_side'],
  212: ['frosted_ice_0','frosted_ice_0','frosted_ice_0','frosted_ice_0','frosted_ice_0','frosted_ice_0'],
  213: ['magma','magma','magma','magma','magma','magma'],
  214: ['nether_wart_block','nether_wart_block','nether_wart_block','nether_wart_block','nether_wart_block','nether_wart_block'],
  215: ['red_nether_brick','red_nether_brick','red_nether_brick','red_nether_brick','red_nether_brick','red_nether_brick'],
  216: ['bone_block_side','bone_block_side','bone_block_top','bone_block_top','bone_block_side','bone_block_side'],
  219: ['shulker_top_white','shulker_top_white','shulker_top_white','shulker_top_white','shulker_top_white','shulker_top_white'],
  220: ['shulker_top_orange','shulker_top_orange','shulker_top_orange','shulker_top_orange','shulker_top_orange','shulker_top_orange'],
  221: ['shulker_top_magenta','shulker_top_magenta','shulker_top_magenta','shulker_top_magenta','shulker_top_magenta','shulker_top_magenta'],
  222: ['shulker_top_light_blue','shulker_top_light_blue','shulker_top_light_blue','shulker_top_light_blue','shulker_top_light_blue','shulker_top_light_blue'],
  223: ['shulker_top_yellow','shulker_top_yellow','shulker_top_yellow','shulker_top_yellow','shulker_top_yellow','shulker_top_yellow'],
  224: ['shulker_top_lime','shulker_top_lime','shulker_top_lime','shulker_top_lime','shulker_top_lime','shulker_top_lime'],
  225: ['shulker_top_pink','shulker_top_pink','shulker_top_pink','shulker_top_pink','shulker_top_pink','shulker_top_pink'],
  226: ['shulker_top_gray','shulker_top_gray','shulker_top_gray','shulker_top_gray','shulker_top_gray','shulker_top_gray'],
  227: ['shulker_top_silver','shulker_top_silver','shulker_top_silver','shulker_top_silver','shulker_top_silver','shulker_top_silver'],
  228: ['shulker_top_cyan','shulker_top_cyan','shulker_top_cyan','shulker_top_cyan','shulker_top_cyan','shulker_top_cyan'],
  229: ['shulker_top_purple','shulker_top_purple','shulker_top_purple','shulker_top_purple','shulker_top_purple','shulker_top_purple'],
  230: ['shulker_top_blue','shulker_top_blue','shulker_top_blue','shulker_top_blue','shulker_top_blue','shulker_top_blue'],
  231: ['shulker_top_brown','shulker_top_brown','shulker_top_brown','shulker_top_brown','shulker_top_brown','shulker_top_brown'],
  232: ['shulker_top_green','shulker_top_green','shulker_top_green','shulker_top_green','shulker_top_green','shulker_top_green'],
  233: ['shulker_top_red','shulker_top_red','shulker_top_red','shulker_top_red','shulker_top_red','shulker_top_red'],
  234: ['shulker_top_black','shulker_top_black','shulker_top_black','shulker_top_black','shulker_top_black','shulker_top_black'],
  235: ['glazed_terracotta_white','glazed_terracotta_white','glazed_terracotta_white','glazed_terracotta_white','glazed_terracotta_white','glazed_terracotta_white'],
  236: ['glazed_terracotta_orange','glazed_terracotta_orange','glazed_terracotta_orange','glazed_terracotta_orange','glazed_terracotta_orange','glazed_terracotta_orange'],
  237: ['glazed_terracotta_magenta','glazed_terracotta_magenta','glazed_terracotta_magenta','glazed_terracotta_magenta','glazed_terracotta_magenta','glazed_terracotta_magenta'],
  238: ['glazed_terracotta_light_blue','glazed_terracotta_light_blue','glazed_terracotta_light_blue','glazed_terracotta_light_blue','glazed_terracotta_light_blue','glazed_terracotta_light_blue'],
  239: ['glazed_terracotta_yellow','glazed_terracotta_yellow','glazed_terracotta_yellow','glazed_terracotta_yellow','glazed_terracotta_yellow','glazed_terracotta_yellow'],
  240: ['glazed_terracotta_lime','glazed_terracotta_lime','glazed_terracotta_lime','glazed_terracotta_lime','glazed_terracotta_lime','glazed_terracotta_lime'],
  241: ['glazed_terracotta_pink','glazed_terracotta_pink','glazed_terracotta_pink','glazed_terracotta_pink','glazed_terracotta_pink','glazed_terracotta_pink'],
  242: ['glazed_terracotta_gray','glazed_terracotta_gray','glazed_terracotta_gray','glazed_terracotta_gray','glazed_terracotta_gray','glazed_terracotta_gray'],
  243: ['glazed_terracotta_silver','glazed_terracotta_silver','glazed_terracotta_silver','glazed_terracotta_silver','glazed_terracotta_silver','glazed_terracotta_silver'],
  244: ['glazed_terracotta_cyan','glazed_terracotta_cyan','glazed_terracotta_cyan','glazed_terracotta_cyan','glazed_terracotta_cyan','glazed_terracotta_cyan'],
  245: ['glazed_terracotta_purple','glazed_terracotta_purple','glazed_terracotta_purple','glazed_terracotta_purple','glazed_terracotta_purple','glazed_terracotta_purple'],
  246: ['glazed_terracotta_blue','glazed_terracotta_blue','glazed_terracotta_blue','glazed_terracotta_blue','glazed_terracotta_blue','glazed_terracotta_blue'],
  247: ['glazed_terracotta_brown','glazed_terracotta_brown','glazed_terracotta_brown','glazed_terracotta_brown','glazed_terracotta_brown','glazed_terracotta_brown'],
  248: ['glazed_terracotta_green','glazed_terracotta_green','glazed_terracotta_green','glazed_terracotta_green','glazed_terracotta_green','glazed_terracotta_green'],
  249: ['glazed_terracotta_red','glazed_terracotta_red','glazed_terracotta_red','glazed_terracotta_red','glazed_terracotta_red','glazed_terracotta_red'],
  250: ['glazed_terracotta_black','glazed_terracotta_black','glazed_terracotta_black','glazed_terracotta_black','glazed_terracotta_black','glazed_terracotta_black'],
  251: ['concrete_white','concrete_white','concrete_white','concrete_white','concrete_white','concrete_white'],
  252: ['concrete_powder_white','concrete_powder_white','concrete_powder_white','concrete_powder_white','concrete_powder_white','concrete_powder_white'],
  255: ['structure_block','structure_block','structure_block','structure_block','structure_block','structure_block'],
}

// Which world axis a block's "front" points to before per-instance facing rotation.
const AXIS_Y = new THREE.Vector3(0, 1, 0)
const AXIS_Z = new THREE.Vector3(0, 0, 1)
export function frontAxis(blockId: number): THREE.Vector3 | null {
  if (blockId === 33 || blockId === 29 || blockId === 34) return AXIS_Y // pistons
  if (blockId === 218) return AXIS_Z // observer
  return null // non-directional: no rotation
}

const CUTOUT = new Set([20, 95, 102, 160]) // glass + stained_glass/glass_pane/stained_glass_pane (reuse glass's texture)
const TRANSLUCENT = new Set([165]) // slime: semi-transparent

const N = 15 // atlas grid (15x15 = 225 cells, 211 used)
const CELL = 16

export interface BlockAssets {
  geo(blockId: number): THREE.BufferGeometry
  material(blockId: number): THREE.Material
  // A full observer-shaped box using DABB's "powered" reskin (all 4 distinct faces, not just the
  // back) - overlaid exactly on top of a real observer instance (same position/facing quaternion)
  // and scaled to 0/1 to show/hide, in place of a colored glow, so the "on" state reads as the
  // actual Minecraft indicator. polygonOffset on the material keeps it winning the z-fight against
  // the real block underneath without needing to enlarge the geometry (which would show edges).
  observerOnGeo: THREE.BufferGeometry
  observerOnMat: THREE.Material
  // A piston body's face while extended (the head has slid away, exposing the plain track
  // texture instead of the piston-top/sticky face) - keyed by the piston's own blockId (29
  // sticky, 33 regular) since each has a different side texture. Overlaid the same way as
  // observerOnGeo/observerOnMat (polygonOffset, no size change).
  pistonInnerGeo(blockId: number): THREE.BufferGeometry | undefined
  pistonInnerMat: THREE.Material
  dispose(): void
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image()
    img.onload = () => resolve(img)
    img.onerror = () => reject(new Error(`failed to load ${src}`))
    img.src = src
  })
}

function cellOf(name: TexName): { col: number; row: number } {
  const i = TEX_NAMES.indexOf(name)
  return { col: i % N, row: Math.floor(i / N) }
}

export async function loadBlockAssets(base: string): Promise<BlockAssets> {
  const imgs = await Promise.all(TEX_NAMES.map((n) => loadImage(`${base}textures/${n}.png`)))

  const canvas = document.createElement('canvas')
  canvas.width = N * CELL
  canvas.height = N * CELL
  const ctx = canvas.getContext('2d')!
  ctx.imageSmoothingEnabled = false
  imgs.forEach((img, i) => {
    const col = i % N
    const row = Math.floor(i / N)
    const frame = Math.min(img.width, img.height) // first frame if animated (tall strip)
    ctx.drawImage(img, 0, 0, img.width, frame, col * CELL, row * CELL, CELL, CELL)
  })

  const atlas = new THREE.CanvasTexture(canvas)
  atlas.magFilter = THREE.NearestFilter
  atlas.minFilter = THREE.NearestFilter
  atlas.generateMipmaps = false
  atlas.colorSpace = THREE.SRGBColorSpace
  atlas.wrapS = atlas.wrapT = THREE.ClampToEdgeWrapping

  const PAD = 0.5 / CELL // half-texel inset so nearest sampling never bleeds into the next cell
  // size/offset let non-cube blocks (rails, trapdoors, fence gates, a piston head's cap/rod) bake
  // a squashed/shifted box instead of a full unit cube - BoxGeometry's 24-vertex/6-face layout is
  // identical regardless of dimensions, so the UV-baking loop below needs no changes for this.
  function bake(
    faces: readonly TexName[],
    size: readonly [number, number, number] = [1, 1, 1],
    offset: readonly [number, number, number] = [0, 0, 0],
  ): THREE.BufferGeometry {
    const geo = new THREE.BoxGeometry(...size)
    const uv = geo.attributes.uv as THREE.BufferAttribute
    for (let f = 0; f < 6; f++) {
      const { col, row } = cellOf(faces[f])
      for (let k = 0; k < 4; k++) {
        const idx = f * 4 + k
        const fu = PAD + uv.getX(idx) * (1 - 2 * PAD)
        const fv = PAD + uv.getY(idx) * (1 - 2 * PAD)
        uv.setXY(idx, (col + fu) / N, (N - 1 - row + fv) / N)
      }
    }
    uv.needsUpdate = true
    if (offset[0] || offset[1] || offset[2]) geo.translate(...offset)
    return geo
  }

  const geos = new Map<number, THREE.BufferGeometry>()
  for (const id of Object.keys(FACES)) geos.set(Number(id), bake(FACES[Number(id)]))
  const fallbackGeo = bake(FACES[1]) // unknown ids render as stone

  // Non-cube blocks: still one geometry per id (shared across all instances, like every other
  // block), just squashed/offset instead of a full unit cube - a shape approximation (real
  // rotation-dependent placement like an open trapdoor or a curved rail isn't modeled), but reads
  // as the right kind of thing instead of a solid block.
  const RAIL_IDS = [27, 28, 66, 157] // golden/detector/rail/activator - thin plate on the floor
  for (const id of RAIL_IDS) {
    if (FACES[id]) geos.set(id, bake(FACES[id], [1, 1 / 16, 1], [0, -0.5 + 1 / 32, 0]))
  }
  const TRAPDOOR_IDS = [96, 167] // closed, bottom-attached (the common case) - thin panel on the floor
  for (const id of TRAPDOOR_IDS) {
    if (FACES[id]) geos.set(id, bake(FACES[id], [1, 3 / 16, 1], [0, -0.5 + 3 / 32, 0]))
  }
  const FENCE_GATE_IDS = [107, 183, 184, 185, 186, 187] // closed - a thin post/bar slab, not a solid block
  for (const id of FENCE_GATE_IDS) {
    if (FACES[id]) geos.set(id, bake(FACES[id], [1, 1, 3 / 16], [0, 0, 0]))
  }

  // Piston head: a thin cap (the visible face) plus a narrower rod reaching back toward the body -
  // two boxes merged into one geometry, each baked/UV-mapped the same way as any other block.
  geos.set(
    34,
    mergeGeometries([
      bake(['piston_side', 'piston_side', 'piston_side', 'piston_side', 'piston_top', 'piston_side'], [1, 1, 4 / 16], [0, 0, 0.5 - 2 / 16]),
      bake(['piston_side', 'piston_side', 'piston_side', 'piston_side', 'piston_side', 'piston_side'], [4 / 16, 4 / 16, 12 / 16], [0, 0, -0.125]),
    ]),
  )

  // Observer "on" box - same face layout as FACES[218] (side/side/top/top/front/back) but using
  // the DABB-powered variant of every face, baked with the same helper as any other block.
  const observerOnGeo = bake(['observer_side_on', 'observer_side_on', 'observer_top_on', 'observer_top_on', 'observer_front_on', 'observer_back_on'])
  const observerOnMat = new THREE.MeshLambertMaterial({
    map: atlas,
    polygonOffset: true, // wins the z-fight against the real (identically-sized/positioned) observer underneath
    polygonOffsetFactor: -4,
    polygonOffsetUnits: -4,
  })

  const pistonInnerGeos = new Map<number, THREE.BufferGeometry>([
    [33, bake(['piston_side', 'piston_side', 'piston_side', 'piston_side', 'piston_inner', 'piston_side'])],
    [29, bake(['piston_side_sticky', 'piston_side_sticky', 'piston_side_sticky', 'piston_side_sticky', 'piston_inner', 'piston_side_sticky'])],
  ])
  const pistonInnerMat = new THREE.MeshLambertMaterial({
    map: atlas,
    polygonOffset: true, // wins the z-fight against the real (identically-sized/positioned) piston body underneath
    polygonOffsetFactor: -4,
    polygonOffsetUnits: -4,
  })

  const matOpaque = new THREE.MeshLambertMaterial({ map: atlas })
  const matCutout = new THREE.MeshLambertMaterial({ map: atlas, alphaTest: 0.5 })
  const matTranslucent = new THREE.MeshLambertMaterial({
    map: atlas,
    transparent: true,
    depthWrite: false, // avoid translucent panels blocking each other's depth
  })

  return {
    geo: (id) => geos.get(id) ?? fallbackGeo,
    material: (id) =>
      CUTOUT.has(id) ? matCutout : TRANSLUCENT.has(id) ? matTranslucent : matOpaque,
    observerOnGeo,
    observerOnMat,
    pistonInnerGeo: (id) => pistonInnerGeos.get(id),
    pistonInnerMat,
    dispose() {
      atlas.dispose()
      for (const g of geos.values()) g.dispose()
      fallbackGeo.dispose()
      observerOnGeo.dispose()
      observerOnMat.dispose()
      for (const g of pistonInnerGeos.values()) g.dispose()
      pistonInnerMat.dispose()
      matOpaque.dispose()
      matCutout.dispose()
      matTranslucent.dispose()
    },
  }
}
